In [1]:
import numpy as np
import tensorflow as tf

In [2]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense

In [3]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

In [4]:
vocab_size = 10000
max_length = 200

(X_train, y_train), (X_test, y_test) = imdb.load_data(
    num_words=vocab_size
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training samples: 25000
Testing samples: 25000


In [5]:
X_train = pad_sequences(
    X_train,
    maxlen=max_length,
    padding='post'
)

X_test = pad_sequences(
    X_test,
    maxlen=max_length,
    padding='post'
)

print(X_train.shape)
print(X_test.shape)

(25000, 200)
(25000, 200)


In [6]:
rnn_model = Sequential([
    Embedding(vocab_size, 128, input_length=max_length),
    SimpleRNN(64),
    Dense(1, activation='sigmoid')
])

rnn_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

rnn_model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
history_rnn = rnn_model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 34s 102ms/step - accuracy: 0.5544 - loss: 0.6770 - val_accuracy: 0.5922 - val_loss: 0.6769
Epoch 2/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 30s 97ms/step - accuracy: 0.6156 - loss: 0.6391 - val_accuracy: 0.6082 - val_loss: 0.6088
Epoch 3/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 31s 100ms/step - accuracy: 0.6503 - loss: 0.5577 - val_accuracy: 0.5986 - val_loss: 0.6467
Epoch 4/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 31s 99ms/step - accuracy: 0.7056 - loss: 0.4465 - val_accuracy: 0.5440 - val_loss: 0.7918
Epoch 5/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 30s 97ms/step - accuracy: 0.7241 - loss: 0.4077 - val_accuracy: 0.5814 - val_loss: 0.7707


In [8]:
lstm_model = Sequential([
    Embedding(vocab_size, 128, input_length=max_length),
    LSTM(64),
    Dense(1, activation='sigmoid')
])

lstm_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
history_lstm = lstm_model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 92s 287ms/step - accuracy: 0.5900 - loss: 0.6501 - val_accuracy: 0.6038 - val_loss: 0.6304
Epoch 2/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 84s 270ms/step - accuracy: 0.6772 - loss: 0.5713 - val_accuracy: 0.6210 - val_loss: 0.5963
Epoch 3/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 86s 275ms/step - accuracy: 0.6944 - loss: 0.5240 - val_accuracy: 0.8242 - val_loss: 0.4532
Epoch 4/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 143s 278ms/step - accuracy: 0.7753 - loss: 0.4938 - val_accuracy: 0.7168 - val_loss: 0.5819
Epoch 5/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 89s 286ms/step - accuracy: 0.7463 - loss: 0.4937 - val_accuracy: 0.7222 - val_loss: 0.6400


In [10]:
gru_model = Sequential([
    Embedding(vocab_size, 128, input_length=max_length),
    GRU(64),
    Dense(1, activation='sigmoid')
])

gru_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

gru_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
history_gru = gru_model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

Epoch 1/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 96s 299ms/step - accuracy: 0.5760 - loss: 0.6606 - val_accuracy: 0.5646 - val_loss: 0.6640
Epoch 2/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 93s 299ms/step - accuracy: 0.7166 - loss: 0.5153 - val_accuracy: 0.8476 - val_loss: 0.3587
Epoch 3/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 142s 300ms/step - accuracy: 0.8979 - loss: 0.2561 - val_accuracy: 0.8586 - val_loss: 0.3359
Epoch 4/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 141s 298ms/step - accuracy: 0.9456 - loss: 0.1552 - val_accuracy: 0.8862 - val_loss: 0.2986
Epoch 5/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 93s 298ms/step - accuracy: 0.9729 - loss: 0.0911 - val_accuracy: 0.8752 - val_loss: 0.3816


In [12]:
rnn_pred = (rnn_model.predict(X_test) > 0.5).astype(int)
lstm_pred = (lstm_model.predict(X_test) > 0.5).astype(int)
gru_pred = (gru_model.predict(X_test) > 0.5).astype(int)

782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step
782/782 ━━━━━━━━━━━━━━━━━━━━ 28s 35ms/step
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 31ms/step


In [13]:
def evaluate_model(name, y_true, y_pred):

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    print("\n", name)
    print("-" * 30)
    print("Accuracy :", accuracy)
    print("Precision:", precision)
    print("Recall   :", recall)
    print("F1 Score :", f1)

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))

In [14]:
evaluate_model("RNN", y_test, rnn_pred)

evaluate_model("LSTM", y_test, lstm_pred)

evaluate_model("GRU", y_test, gru_pred)


 RNN
------------------------------
Accuracy : 0.57184
Precision: 0.6618018018018018
Recall   : 0.29384
F1 Score : 0.40698060941828257

Confusion Matrix:
[[10623  1877]
 [ 8827  3673]]

 LSTM
------------------------------
Accuracy : 0.72832
Precision: 0.6564007014467339
Recall   : 0.95824
F1 Score : 0.7791075842331209

Confusion Matrix:
[[ 6230  6270]
 [  522 11978]]

 GRU
------------------------------
Accuracy : 0.86656
Precision: 0.8395080023710729
Recall   : 0.9064
F1 Score : 0.8716725650100016

Confusion Matrix:
[[10334  2166]
 [ 1170 11330]]
